# Generated by Django 4.0.3 on 2022-04-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoint_id', models.IntegerField()),
                ('medicine_id', models.IntegerField()),
                ('order_num', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoint_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='appointmentrecord',
            name='ill_type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrecord',
            name='patient_description',
            field=models.TextField(default=None, null=True),
        ),
    ]
