# Generated by Django 4.0.3 on 2022-04-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_condition_orderrecord_raterecord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentrecord',
            old_name='ill_type',
            new_name='condition',
        ),
    ]
